version: "3"
volumes:
    # Путь к локальной директории public_html
    public_html:
    # Путь к файлам данных БД
    database:
    # Путь к xdebug логам
    xdebug:
    # Путь к sphinx БД
    sphinx:
    # Путь к БД redis
    redis:

services:
    nginx:
        build:
            context: ../.images/nginx
        image: nginx
        container_name: nginx
        volumes:
            - ${DOCUMENT_ROOT}:/var/www:ro
        ports:
            - "80:80"
        links:
            - fpm:fpm
            - memcached:memcached
            - logger
        networks:
            - net
        restart: unless-stopped
        logging:
            driver: "syslog"
            options:
                syslog-address: "udp://127.0.0.1:5514"
                syslog-facility: "daemon"
                tag: "nginx"

    fpm:
        build:
            context: ../.images/php7-fpm
        image: php7-fpm
        container_name: php7-fpm
        volumes:
            - ${DOCUMENT_ROOT}:/var/www
            - ${DATA_XDEBUG}:/tmp/xdebug
        ports:
            - "9000:9000"
        links:
            - db:db
            - memcached:memcached
            - sphinx:sphinx
            - logger
        networks:
            - net
        restart: unless-stopped
        logging:
            driver: "syslog"
            options:
                syslog-address: "udp://127.0.0.1:5514"
                syslog-facility: "daemon"
                tag: "php7-fpm"

    crontab:
        build:
            context: ../.images/php7-cron
        image: php7-cron
        container_name: php7-cron
        volumes:
            - ${DOCUMENT_ROOT}:/var/www
            - ${DATA_XDEBUG}:/tmp/xdebug
        links:
            - db:db
            - memcached:memcached
            - sphinx:sphinx
            - logger
        networks:
            - net
        restart: unless-stopped
        logging:
            driver: "syslog"
            options:
                syslog-address: "udp://127.0.0.1:5514"
                syslog-facility: "daemon"
                tag: "php7-cron"

    db:
        build:
            context: ../.images/percona5.6
        image: percona:5.6
        container_name: percona_db
        volumes:
            - ${DATA_MYSQL}:/var/lib/mysql
            - ../.conf/percona:/etc/mysql/conf.d
            - ../.conf/percona:/docker-entrypoint-initdb.d
        ports:
            - "11212:11212"
            - "3306:3306"
            - "9999:9999"
            - "9998:9998"
        links:
            - logger
        networks:
            - net
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        restart: unless-stopped
        logging:
            driver: "syslog"
            options:
                syslog-address: "udp://127.0.0.1:5514"
                syslog-facility: "daemon"
                tag: "percona"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        links:
            - db:db
        ports:
            - "8081:80"
        networks:
            - net
        environment:
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        restart: unless-stopped

    memcached:
        image: memcached
        container_name: memcached
        ports:
            - "11211:11211"
        links:
            - logger
        networks:
            - net
        restart: unless-stopped
        logging:
            driver: "syslog"
            options:
                syslog-address: "udp://127.0.0.1:5514"
                syslog-facility: "daemon"
                tag: "memcached"

    redis:
        build:
            context: ../.images/redis
        image: redis
        container_name: redis
        volumes:
            - ${DATA_REDIS}:/tmp/redis
        ports:
            - "6379:6379"
        links:
            - logger
        networks:
            - net
        restart: unless-stopped
        logging:
            driver: "syslog"
            options:
                syslog-address: "udp://127.0.0.1:5514"
                syslog-facility: "daemon"
                tag: "redis"

    phpredadmin:
        image: faktiva/php-redis-admin
        environment:
            - PHPREDMIN_DATABASE_REDIS_0_HOST=redis
        ports:
            - "8082:80"
        depends_on:
            - redis
        links:
            - logger
        networks:
            - net
        restart: unless-stopped
        logging:
            driver: "syslog"
            options:
                syslog-address: "udp://127.0.0.1:5514"
                syslog-facility: "daemon"
                tag: "phpredadmin"

    sphinx:
        build:
            context: ../.images/sphinx
        #image: sphinx
        container_name: sphinx
        depends_on:
          - "db"
        volumes:
            - ${DATA_SPHINX}:/var/lib/sphinxsearch/data
        ports:
            - "9312:9312"
            - "9306:9306"
        links:
            - logger
            - db
        networks:
            - net
        restart: unless-stopped
        logging:
            driver: "syslog"
            options:
                syslog-address: "udp://127.0.0.1:5514"
                syslog-facility: "daemon"
                tag: "sphinx"

    pinba:
        build:
            context: ../.images/pinba_mysql
        #image: pinba
        container_name: pinba
        volumes:
            - ${DATA_PINBA}:/var/lib/mysql
            #- ../.conf/pinba:/etc/mysql/conf.d
            #- ../.conf/percona:/docker-entrypoint-initdb.d
        ports:
            - "30001:30002/udp"
            - "3006:3306"
        links:
            - logger
        networks:
            - net
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            PINBA_STATS_GATHERING_PERIOD: 10000
            PINBA_STATS_HISTORY: 900
            PINBA_TEMP_POOL_SIZE: 10000
            PINBA_REQUEST_POOL_SIZE: 1000000
            #PINBA_HISTOGRAM_MAX_TIME
        restart: unless-stopped
        logging:
            driver: "syslog"
            options:
                syslog-address: "udp://127.0.0.1:5514"
                syslog-facility: "daemon"
                tag: "pinba"

    pinba_tony:
        build:
            context: ../.images/pinba_tony
        #image: pinba
        container_name: pinba_tony
        volumes:
            - ${DATA_PINBA_TONY}:/var/lib/mysql
            #- ../.conf/pinba:/etc/mysql/conf.d
            #- ../.conf/percona:/docker-entrypoint-initdb.d
        ports:
            - "30002:30002/udp"
            - "3003:3306"
        links:
            - logger
        networks:
            - net
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            PINBA_STATS_GATHERING_PERIOD: 10000
            PINBA_STATS_HISTORY: 900
            PINBA_TEMP_POOL_SIZE: 10000
            PINBA_REQUEST_POOL_SIZE: 1000000
            #PINBA_HISTOGRAM_MAX_TIME
        restart: unless-stopped
        logging:
            driver: "syslog"
            options:
                syslog-address: "udp://127.0.0.1:5514"
                syslog-facility: "daemon"
                tag: "pinba_tony"

    logger:
        image: voxxit/rsyslog
        container_name: logger
        volumes:
            - ${LOG_DIR}:/var/log
        ports:
            - "127.0.0.1:5514:514/udp"
        networks:
            - net
        restart: unless-stopped

networks:
    net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.17.1/24
#                  aux_addresses:
#                      db: 192.168.17.33
