version: "3"
volumes:
    # Путь к БД redis
    redis:
    # Pinba DB
    pinba:
    # Pinboard web
    pinboard:
    # Nodejs
    nodejs:

services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        volumes:
            - ${MP_CONF}:/etc/nginx/nginx.conf
            - ${MP_WEB}:/var/www/magicpro:ro
            - ${HOSTS_CONF}:/etc/nginx/conf.d:ro
            - ${HOSTS_WEB}:/var/www/hosts:ro
        #command: [nginx-debug, '-g', 'daemon off;']
        command: [ nginx, '-g', 'daemon off;' ]
        ports:
            - "80:80"
        networks:
            - net
        restart: unless-stopped
        logging:
            driver: "syslog"
            options:
                syslog-address: "udp://127.0.0.1:5514"
                syslog-facility: "daemon"
                tag: "nginx"

    fpm:
        image: fpm
        build:
            context: ../../images/php/serv
            dockerfile: ./php-fpm/Dockerfile
            args:
                # build context only
                php_version: ${PHP_VERSION:-8.1}
                allow_xdebug: ${ALLOW_XDEBUG:-1}
        container_name: php-fpm
        environment:
            # service container environment
            - PHP_VERSION=${PHP_VERSION:-8.1}
            - XDEBUG_PORT=${XDEBUG_PORT:-9001}
        volumes:
            - ${MP_WEB}:/var/www/magicpro
            - ${HOSTS_WEB}:/var/www/hosts
            - ${DATA_XDEBUG}:/tmp/xdebug
        ports:
            - "9000:9000"
        links:
            - "mercure:mercure"
        networks:
            - net
        restart: unless-stopped
        logging:
            driver: "syslog"
            options:
                syslog-address: "udp://127.0.0.1:5514"
                syslog-facility: "daemon"
                tag: "{{.ImageName}}"

    crontab:
        image: cron
        build:
            context: ../../images/php/serv
            dockerfile: ./php-cron/Dockerfile
            args:
                - php_version=${PHP_VERSION:-8.1}
                - allow_xdebug=${ALLOW_XDEBUG:-1}
        container_name: php-cron
        environment:
            PHP_VERSION: ${PHP_VERSION:-8.1}
            XDEBUG_PORT: ${XDEBUG_PORT:-9001}
        volumes:
            - ${MP_WEB}:/var/www
            - ${DATA_XDEBUG}:/tmp/xdebug
        networks:
            - net
        restart: unless-stopped
        logging:
            driver: "syslog"
            options:
                syslog-address: "udp://127.0.0.1:5514"
                syslog-facility: "daemon"
                tag: "{{.ImageName}}"

    db:
        image: percona:5.7
        container_name: percona_db
        volumes:
            - ${DATA_MYSQL}:/var/lib/mysql
            - ${MYSQL_CONF}:/etc/my.cnf.d:ro
        ports:
            - "3306:3306"
        links:
            - "logger"
        networks:
            net:
                ipv4_address: 192.168.17.33
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        restart: unless-stopped
        logging:
            driver: "syslog"
            options:
                syslog-address: "udp://127.0.0.1:5514"
                syslog-facility: "daemon"
                tag: "{{.ImageName}}"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        links:
            - db:db
        ports:
            - "8081:80"
        networks:
            - net
        environment:
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            UPLOAD_LIMIT: ${UPLOAD_LIMIT}
        restart: unless-stopped

    memcached:
        image: memcached
        container_name: memcached
        ports:
            - "11211:11211"
        networks:
            - net
        restart: unless-stopped
        logging:
            driver: "syslog"
            options:
                syslog-address: "udp://127.0.0.1:5514"
                syslog-facility: "daemon"
                tag: "{{.ImageName}}"

    redis:
        image: redis
        build:
            context: ../../images/redis
        container_name: redis
        volumes:
            - ${DATA_REDIS}:/tmp/redis
        ports:
            - "6379:6379"
        networks:
            - net
        restart: unless-stopped
        logging:
            driver: "syslog"
            options:
                syslog-address: "udp://127.0.0.1:5514"
                syslog-facility: "daemon"
                tag: "{{.ImageName}}"

    phpredadmin:
        image: faktiva/php-redis-admin
        container_name: phpredadmin
        environment:
            - PHPREDMIN_DATABASE_REDIS_0_HOST=redis
        ports:
            - "8082:80"
        depends_on:
            - redis
        networks:
            - net
        restart: unless-stopped
        logging:
            driver: "syslog"
            options:
                syslog-address: "udp://127.0.0.1:5514"
                syslog-facility: "daemon"
                tag: "{{.ImageName}}"

    sphinx:
        image: sphinx
        build:
            context: ../../images/sphinx
        container_name: sphinx
        depends_on:
            - "db"
        volumes:
            - ${MP_WEB}:/var/www/magicpro
            - ${DATA_SPHINX}:/var/lib/sphinxsearch/data
        ports:
            - "9312:9312"
            - "9306:9306"
        networks:
            - net
        restart: unless-stopped
        logging:
            driver: "syslog"
            options:
                syslog-address: "udp://127.0.0.1:5514"
                syslog-facility: "daemon"
                tag: "{{.ImageName}}"

    elastic: # sudo sysctl -w vm.max_map_count=262144
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
        container_name: elastic
        environment:
            - node.name=es01
            - cluster.name=es-docker-cluster
            - cluster.initial_master_nodes=es01
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - "9200"
        networks:
            - net
        depends_on:
            - "db"
        volumes:
            - ${MP_WEB}:/var/www/magicpro:ro
            - ${DATA_ELASTIC}:/usr/share/elasticsearch/data
        restart: unless-stopped
        logging:
            driver: "syslog"
            options:
                syslog-address: "udp://127.0.0.1:5514"
                syslog-facility: "daemon"
                tag: "{{.ImageName}}"

    nodejs:
        image: nodejs
        build:
            context: ../../images/nodejs
        container_name: nodejs
        ports:
            - "8085:8085"
            - "8086:8086"
            - "1333:1333"
        networks:
            - net
        restart: unless-stopped
        logging:
            driver: "syslog"
            options:
                syslog-address: "udp://127.0.0.1:5514"
                syslog-facility: "daemon"
                tag: "{{.ImageName}}"

    pinba:
        image: tony2001/pinba
        build:
            context: ../../images/pinba
        container_name: pinba
        volumes:
            - pinba:/local/mysql/data
        ports:
            - "30002:30002/udp"
            - "3006:3306"
        networks:
            - net
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            PINBA_STATS_GATHERING_PERIOD: 10000
            PINBA_STATS_HISTORY: 300
            PINBA_TEMP_POOL_SIZE: 10000
            PINBA_REQUEST_POOL_SIZE: 1000000
            #PINBA_HISTOGRAM_MAX_TIME
        restart: unless-stopped
        logging:
            driver: "syslog"
            options:
                syslog-address: "udp://127.0.0.1:5514"
                syslog-facility: "daemon"
                tag: "{{.ImageName}}"

    pinboard:
        image: pinboard
        build:
            context: ../../images/pinboard
        container_name: pinboard
        volumes:
            - pinboard:/www
        ports:
            - "8084:8080"
        networks:
            - net
        environment:
            MYSQL_HOST: "pinba"
            MYSQL_USER: "root"
            MYSQL_PASSWORD: ""
            AGGREGATION_PERIOD: 5
        restart: unless-stopped
        logging:
            driver: "syslog"
            options:
                syslog-address: "udp://127.0.0.1:5514"
                syslog-facility: "daemon"
                tag: "{{.ImageName}}"

    # https://github.com/dunglas/mercure
    mercure:
        image: dunglas/mercure
        container_name: mercure
        volumes:
            - ${MERCURE_CONFIG}:/etc/caddy/Caddyfile.dev
        environment:
            # Uncomment the following line to disable HTTPS
            SERVER_NAME: ':80'
            MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_KEY}
            MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_KEY}
            # Uncomment the following line to enable the development mode
            command: /usr/bin/caddy run -config /etc/caddy/Caddyfile.dev
        ports:
            - "8088:80"
            - "8443:443"
        links:
            - logger
        networks:
            - net
        restart: unless-stopped
        logging:
            driver: "syslog"
            options:
                syslog-address: "udp://127.0.0.1:5514"
                syslog-facility: "daemon"
                tag: "{{.ImageName}}"

    logger:
        image: lscr.io/linuxserver/syslog-ng:latest
        container_name: logger
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Moscow
        volumes:
            - ${LOG_CONFIG}:/config/syslog-ng.conf
            - ${LOG_DIR}:/var/log #optional
        ports:
            - "127.0.0.1:5514:5514/udp"
            - "127.0.0.1:6601:6601/tcp"
            - 514:5514/udp
            - 601:6601/tcp
            - 6514:6514/tcp
        networks:
            - net
        restart: unless-stopped

networks:
    net:
        #        name: dockerNet
        driver: bridge
        ipam:
            driver: default
            config:
                -   subnet: 192.168.17.1/24
