FROM tarantool/tarantool:2
MAINTAINER gimatov@gmail.com

# https://docs.docker.com/engine/faq/
ENV DEBIAN_FRONTEND=noninteractive

# Expose ports
EXPOSE 3301

#COPY app.lua /opt/tarantool
#CMD ["tarantool", "/opt/tarantool/app.lua"]