version: "3"
volumes:
    # Путь к БД redis
    redis:

services:
    nginx:
        build:
            context: ../.images/nginx
        image: nginx
        container_name: nginx
        volumes:
            - ${DOCUMENT_ROOT}:/var/www:ro
        ports:
            - "80:80"
        links:
            - fpm:fpm
            - memcached:memcached
            - logger
        networks:
            - net
        restart: unless-stopped
        logging:
            driver: "syslog"
            options:
                syslog-address: "udp://127.0.0.1:5514"
                syslog-facility: "daemon"
                tag: "nginx"

    fpm:
        build:
            context: ../.images/php
            dockerfile: ./php5-fpm/Dockerfile
        container_name: php5-fpm
        volumes:
            - ${DOCUMENT_ROOT}:/var/www
            - ${DATA_XDEBUG}:/tmp/xdebug
        ports:
            - "9000:9000"
        links:
            - db:db
            - memcached:memcached
            - sphinx:sphinx
            - logger
        networks:
            - net
        restart: unless-stopped
        logging:
            driver: "syslog"
            options:
                syslog-address: "udp://127.0.0.1:5514"
                syslog-facility: "daemon"
                tag: "php5-fpm"

    crontab:
        build:
            context: ../.images/php
            dockerfile: ./php5-cron/Dockerfile
        container_name: php5-cron
        volumes:
            - ${DOCUMENT_ROOT}:/var/www
            - ${DATA_XDEBUG}:/tmp/xdebug
        links:
            - db:db
            - memcached:memcached
            - sphinx:sphinx
            - logger
        networks:
            - net
        restart: unless-stopped
        logging:
            driver: "syslog"
            options:
                syslog-address: "udp://127.0.0.1:5514"
                syslog-facility: "daemon"
                tag: "php5-cron"

    db:
        build:
            context: ../.images/percona5.6
        image: percona:5.6
        container_name: percona_db
        volumes:
            - ${DATA_MYSQL}:/var/lib/mysql
        ports:
            - "11212:11212"
            - "3306:3306"
            - "9999:9999"
            - "9998:9998"
        links:
            - logger
        networks:
            - net
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        restart: unless-stopped
        logging:
            driver: "syslog"
            options:
                syslog-address: "udp://127.0.0.1:5514"
                syslog-facility: "daemon"
                tag: "percona"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        links:
            - db:db
        ports:
            - "8081:80"
        networks:
            - net
        environment:
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        restart: unless-stopped

    memcached:
        image: memcached
        container_name: memcached
        ports:
            - "11211:11211"
        links:
            - logger
        networks:
            - net
        restart: unless-stopped
        logging:
            driver: "syslog"
            options:
                syslog-address: "udp://127.0.0.1:5514"
                syslog-facility: "daemon"
                tag: "memcached"

    redis:
        build:
            context: ../.images/redis
        image: redis
        container_name: redis
        volumes:
            - ${DATA_REDIS}:/tmp/redis
        ports:
            - "6379:6379"
        links:
            - logger
        networks:
            - net
        restart: unless-stopped
        logging:
            driver: "syslog"
            options:
                syslog-address: "udp://127.0.0.1:5514"
                syslog-facility: "daemon"
                tag: "redis"

    phpredadmin:
        image: faktiva/php-redis-admin
        environment:
            - PHPREDMIN_DATABASE_REDIS_0_HOST=redis
        ports:
            - "8082:80"
        depends_on:
            - redis
        links:
            - logger
        networks:
            - net
        restart: unless-stopped
        logging:
            driver: "syslog"
            options:
                syslog-address: "udp://127.0.0.1:5514"
                syslog-facility: "daemon"
                tag: "phpredadmin"

    sphinx:
        build:
            context: ../.images/sphinx
        container_name: sphinx
        depends_on:
          - "db"
        volumes:
            - ${DATA_SPHINX}:/var/lib/sphinxsearch/data
            - ${DOCUMENT_ROOT}:/var/www:ro
        ports:
            - "9312:9312"
            - "9306:9306"
        links:
            - logger
            - db
        networks:
            - net
        restart: unless-stopped
        logging:
            driver: "syslog"
            options:
                syslog-address: "udp://127.0.0.1:5514"
                syslog-facility: "daemon"
                tag: "sphinx"

    logger:
        image: voxxit/rsyslog
        container_name: logger
        volumes:
            - /var/log/docker:/var/log
        ports:
            - "127.0.0.1:5514:514/udp"
        networks:
            - net
        restart: unless-stopped

networks:
    net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.17.1/24
#                  aux_addresses:
#                      db: 192.168.17.33
